theme: jekyll-theme-merlot
title: Welcome to GavinMcGahey's first GitHub Page!
description: This is GavinMcGahey's first GitHub page. This is just a learning platform for now, but be on the lookout for a real webpage dropping soon!
